const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execSync } = require('child_process');

// Rutas base
const SERVER_DIR = path.resolve(__dirname, '..');
const KEYS_DIR = path.join(SERVER_DIR, 'keys');
const PRIVATE_KEY_PATH = path.join(KEYS_DIR, 'private.pem');
const CDN_DIR = path.join(SERVER_DIR, 'public', 'cdn');
const GODOT_PROJECT_DIR = path.resolve(SERVER_DIR, '../descon');
const PUBLIC_KEY_GD_PATH = path.join(GODOT_PROJECT_DIR, 'scripts', 'autoloads', 'PublicKey.gd');

// Configuración de Godot
const DEFAULT_GODOT_PATH = 'E:\\PROGRAMAS\\Godot\\Godot_v4.7-stable_win64.exe';
const GODOT_BIN = process.env.GODOT_BIN || (fs.existsSync(DEFAULT_GODOT_PATH) ? DEFAULT_GODOT_PATH : 'godot');

console.log('--- SISTEMA DE ACTUALIZACIÓN DESCON V2.0 ---');

// 1. Asegurar directorios
if (!fs.existsSync(KEYS_DIR)) {
    fs.mkdirSync(KEYS_DIR, { recursive: true });
}
if (!fs.existsSync(CDN_DIR)) {
    fs.mkdirSync(CDN_DIR, { recursive: true });
}

// Asegurar .gitignore en la carpeta keys para nunca subir la clave privada
const gitignorePath = path.join(KEYS_DIR, '.gitignore');
if (!fs.existsSync(gitignorePath)) {
    fs.writeFileSync(gitignorePath, 'private.pem\n');
    console.log('[KEYS] Creado .gitignore para la clave privada.');
}

// 2. Generación de claves RSA si no existen
let privateKeyPem;
let publicKeyPem;

if (!fs.existsSync(PRIVATE_KEY_PATH)) {
    console.log('[KEYS] Clave privada no encontrada. Generando nuevo par de claves RSA 2048-bit...');
    const { privateKey, publicKey } = crypto.generateKeyPairSync('rsa', {
        modulusLength: 2048,
        publicKeyEncoding: { type: 'spki', format: 'pem' },
        privateKeyEncoding: { type: 'pkcs8', format: 'pem' }
    });
    
    fs.writeFileSync(PRIVATE_KEY_PATH, privateKey);
    privateKeyPem = privateKey;
    publicKeyPem = publicKey;
    console.log('[KEYS] Nueva clave privada guardada en: ' + PRIVATE_KEY_PATH);
    
    // Escribir PublicKey.gd en el proyecto Godot
    const publicKeyGdContent = `extends Node

# Autogenerated by package_updates.js - DO NOT EDIT MANUALLY
const PUBLIC_KEY_PEM = """${publicKeyPem.trim()}"""
`;
    
    // Asegurar directorio del autoload
    const autoloadsDir = path.dirname(PUBLIC_KEY_GD_PATH);
    if (!fs.existsSync(autoloadsDir)) {
        fs.mkdirSync(autoloadsDir, { recursive: true });
    }
    fs.writeFileSync(PUBLIC_KEY_GD_PATH, publicKeyGdContent);
    console.log('[KEYS] Creado autoload de clave pública en Godot: ' + PUBLIC_KEY_GD_PATH);
} else {
    console.log('[KEYS] Usando clave privada existente.');
    privateKeyPem = fs.readFileSync(PRIVATE_KEY_PATH, 'utf8');
    
    // Obtener la clave pública desde la privada
    const pubKeyObject = crypto.createPublicKey(privateKeyPem);
    publicKeyPem = pubKeyObject.export({ type: 'spki', format: 'pem' });
}

// 3. Exportar PCKs usando Godot
const exportPCK = (presetName, outputPath) => {
    console.log(`[EXPORT] Exportando PCK para preset "${presetName}"...`);
    const fullOutputPath = path.resolve(CDN_DIR, outputPath);
    const cmd = `"${GODOT_BIN}" --headless --path "${GODOT_PROJECT_DIR}" --export-pack "${presetName}" "${fullOutputPath}"`;
    
    try {
        execSync(cmd, { stdio: 'inherit' });
        console.log(`[EXPORT] PCK creado con éxito: ${outputPath}`);
        return true;
    } catch (err) {
        console.warn(`[WARNING] No se pudo exportar automáticamente usando el comando: ${GODOT_BIN}`);
        console.warn(`Detalle: ${err.message}`);
        console.warn(`Asegúrate de tener Godot en tu PATH o configura la variable GODOT_BIN.`);
        return false;
    }
};

// Intentar exportaciones por CLI
const exportedWindows = exportPCK('Descon Windows Patch', 'Actualizacion_Windows.pck');
const exportedAndroid = exportPCK('Descon V2 Patch', 'Actualizacion_Android.pck');

// Rutas de origen de exportación del usuario
const EXPORT_WINDOWS_DIR = path.resolve(SERVER_DIR, '../Ejecutable');
const EXPORT_ANDROID_DIR = path.resolve(SERVER_DIR, '../Ejecutable Android');

// Función para copiar PCKs desde las carpetas de exportación del usuario al CDN
const copyPCKFromExports = () => {
    console.log('[EXPORT] Buscando archivos PCK en las carpetas de exportación del usuario...');
    
    // Windows
    if (!exportedWindows) {
        const winSources = [
            path.join(EXPORT_WINDOWS_DIR, 'Descon.pck'),
            path.join(EXPORT_WINDOWS_DIR, 'Actualizacion_Windows.pck'),
            path.join(EXPORT_WINDOWS_DIR, 'Actualizacion Windows.pck')
        ];
        let winCopied = false;
        for (const src of winSources) {
            if (fs.existsSync(src)) {
                const dest = path.join(CDN_DIR, 'Actualizacion_Windows.pck');
                fs.copyFileSync(src, dest);
                console.log(`[EXPORT] Copiado PCK de Windows de: ${src} -> ${dest}`);
                winCopied = true;
                break;
            }
        }
        if (!winCopied) {
            console.log('[EXPORT] No se encontró un nuevo PCK en la carpeta Ejecutable/ (se usará el existente en CDN si hay).');
        }
    } else {
        console.log('[EXPORT] PCK de Windows exportado por CLI con éxito. Omitiendo copia manual.');
    }

    // Android
    if (!exportedAndroid) {
        const androidSources = [
            path.join(EXPORT_ANDROID_DIR, 'Descon.pck'),
            path.join(EXPORT_ANDROID_DIR, 'Actualizacion_Android.pck'),
            path.join(EXPORT_ANDROID_DIR, 'Actualizacion Android.pck')
        ];
        let androidCopied = false;
        for (const src of androidSources) {
            if (fs.existsSync(src)) {
                const dest = path.join(CDN_DIR, 'Actualizacion_Android.pck');
                fs.copyFileSync(src, dest);
                console.log(`[EXPORT] Copiado PCK de Android de: ${src} -> ${dest}`);
                androidCopied = true;
                break;
            }
        }
        if (!androidCopied) {
            console.log('[EXPORT] No se encontró un nuevo PCK en la carpeta Ejecutable Android/ (se usará el existente en CDN si hay).');
        }
    } else {
        console.log('[EXPORT] PCK de Android exportado por CLI con éxito. Omitiendo copia manual.');
    }
};

// Ejecutar copiado de exportaciones manuales
copyPCKFromExports();

// 4. Firmar y generar manifiesto
const generateManifest = () => {
    console.log('[MANIFEST] Generando manifest.json...');
    const manifest = {
        version: Date.now().toString(), // Usamos timestamp como versión única
        timestamp: Math.floor(Date.now() / 1000),
        packages: {}
    };

    const processFile = (fileName, platformKey) => {
        const filePath = path.join(CDN_DIR, fileName);
        if (!fs.existsSync(filePath)) {
            console.log(`[MANIFEST-WARN] Archivo no encontrado para ${platformKey}: ${fileName}`);
            return;
        }

        const fileBuffer = fs.readFileSync(filePath);
        
        // Calcular SHA-256
        const sha256 = crypto.createHash('sha256').update(fileBuffer).digest('hex');
        
        // Firmar SHA-256 con RSA
        const sign = crypto.createSign('SHA256');
        sign.update(fileBuffer);
        const signatureBase64 = sign.sign(privateKeyPem, 'base64');

        manifest.packages[platformKey] = {
            file: fileName,
            size: fileBuffer.length,
            hash: sha256,
            signature: signatureBase64
        };
        console.log(`[MANIFEST] Procesado ${platformKey}: hash=${sha256.substring(0, 10)}...`);
    };

    processFile('Actualizacion_Windows.pck', 'windows');
    processFile('Actualizacion_Android.pck', 'android');

    const manifestPath = path.join(CDN_DIR, 'manifest.json');
    fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 4));
    console.log(`[MANIFEST] manifest.json generado con éxito en: ${manifestPath}`);
};

generateManifest();
console.log('--- PROCESO TERMINADO ---');
console.log('Nota: Si no se pudieron generar los archivos PCK por falta de Godot CLI,');
console.log('puedes exportarlos manualmente desde el editor de Godot a Server/public/cdn/');
console.log('y volver a ejecutar este script para firmarlos y generar el manifiesto.');
